### ISSUE TITLE
Hello，I what to know some detail about code

### ISSUE THREAD

**Issue by qfxdz** [Mattdl/CLsurvey#1]
Excuse me, I'd like to ask some questions.
1.  Is it true that all data sets are kept at the same size in the experiment?
2. Which labels are adopted in the VOC dataset?
3. Does the experiment provide a mutli-head setting for each method?
--------------------------------------------------------------------------
If you have time, can you help me answer it? Thank you very much.
--------------------------------------------------------------------------

**Comment by Mattdl** [comment]
Hi, thanks for your questions!
All datasets are preprocessed and therefore are of equal size for the experiments. For the VOC dataset, we refer to our main paper which elaborates on the used subset. Each method is considered in the multi-head setting for a fair comparison
