### ISSUE TITLE
How to run the entire pipeline?

### ISSUE THREAD

**Issue by zihuanqiu** [Mattdl/CLsurvey#3]
Hi~
Thanks for your great job. This code is a great help to the community and people who just started.
I have checked the main_tinyimagenet.sh and only find the run with SI and EBLL. Forgive me for just being a newcomer, and I am lost in the code. 
I want to know how to run the whole pipeline with 11 methods reported in your paper.
Thanks!

**Comment by zihuanqiu** [comment]
I studied the code carefully and understood it roughly, but I still couldn't run through the experiment. The code often makes mistakes.

**Comment by Mattdl** [comment]
Hi sorry for the late reply. Have you been able to run the pipeline?
